site_name: npstyping
site_url: https://fherb2.github.io/npstyping/
nav:
  - Home: index.md
  - API:  api.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: ["src"]
            docstring_style: numpy
            members: true
            filters: ["!^_"] # ignores privat methods
