site_name: npstyping
site_url: https://fherb2.github.io/npstyping/
nav:
  - Home: index.md
  - API:  api.md
theme: mkdocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            summary: true
            show_source: false
            parameter_headings: true
          #  show_labels: true
            members_order: alphabetical
            show_bases: false
            group_by_category: true
            show_category_heading: true
            members: true
            filters:
              - "!^_"
              - "!^__"
            extra:
              paths: ["src"]
