site_name: npstyping
site_url: https://fherb2.github.io/npstyping/
nav:
  - Home: index.md
  - API:  api.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            summary: true
            show_source: false
            parameter_headings: false
          #  show_labels: true
            members_order: source
            show_bases: false
            # group_by_category: true
            # show_category_heading: true
            members: false
            filters:
              - "!^_[^_]"
            extra:
              paths: ["src"]
